repos:
  # Core hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: mixed-line-ending

  # Python formatting
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile=black"]

  # Python linting (fast)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        args: ["--fix"]

  # Security (advisory in pre-commit; CI can be gating)
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        name: bandit (security)
        args: ["-q", "-x", "tests"]

  # JavaScript / TypeScript formatting & lint
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.3.3
    hooks:
      - id: prettier
        additional_dependencies: ["prettier@3.3.3"]
        files: "^frontend/"

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.8.0
    hooks:
      - id: eslint
        files: "^frontend/"
        types_or: [javascript, jsx, ts, tsx]
        additional_dependencies:
          - "eslint@9.8.0"
          - "@typescript-eslint/parser@7.17.0"
          - "@typescript-eslint/eslint-plugin@7.17.0"
          - "eslint-config-prettier@9.1.0"

  # Optional: dependency audit (kept light in pre-commit; make CI gating later)
  # pip-audit is heavy and network-bound; keep as manual stage/CI step.
  # npm-audit runs in CI for the frontend once scaffolded.

ci:
  autofix_prs: true
  autofix_commit_msg: "chore(pre-commit): auto-fix issues"
