name: backend-lint-test-mypy
on:
  pull_request:
    paths:
      - "codie-backend/**"
      - "ruff.toml"
      - "pytest.ini"
      - "mypy.ini"
      - ".pre-commit-config.yaml"
  push:
    branches: [main]
    paths:
      - "codie-backend/**"
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r codie-backend/requirements.txt
          python -m pip install ruff mypy pytest
      - name: Ruff lint
        run: ruff check .
      - name: Ruff format check
        run: ruff format --check .
      - name: Pytest
        run: pytest
      - name: Mypy (allow failure initially)
        run: mypy .
        continue-on-error: true
