name: docs-debt-and-lint
on:
  pull_request:
    paths:
      - "docs/**"
  push:
    branches: [main]
    paths:
      - "docs/**"
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v14
        with:
          globs: "docs/**/*.md"
      - name: Fail on DEBT markers
        run: |
          if grep -RIn "DEBT" docs; then
            echo "Documentation debt markers detected (DEBT). Please address or waive."
            exit 1
          fi
          echo "No DEBT markers detected."
